parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: '3306'
    database_name: symfony
    database_user: sysadmin
    database_password: sysadmin
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: fae6c25174fdafacf2d8fe52d071978f
    database_path: null
